"""
Prior-year tax return parser.

Extracts structured data from a TurboTax-generated (or similar) PDF return
using a two-pass approach:
  1. PyMuPDF (fitz) extracts text from the key pages (1040, Schedule 1/2/3, IT-201)
  2. GPT-4o maps the text to the PriorYearReturn schema
"""

from __future__ import annotations

import json
import re
from decimal import Decimal
from pathlib import Path

import fitz  # PyMuPDF

from pfile.models.prior_year import (
    PriorYearForm1040,
    PriorYearIT201,
    PriorYearReturn,
    PriorYearScheduleD,
)
from pfile.parsers.llm import get_client
from pfile.security import redact_pii

# Pages we care about — we search by keyword so exact page numbers don't matter
_WANT_KEYWORDS = {
    "form_1040_p1": ["Total amount from Form(s) W-2", "U.S. Individual Income Tax Return"],
    "form_1040_p2": ["Tax and Credits", "Total tax", "Amount You Owe"],
    "schedule_1": ["SCHEDULE 1", "Additional Income and Adjustments"],
    "schedule_2": ["SCHEDULE 2", "Additional Taxes"],
    "schedule_3": ["SCHEDULE 3", "Additional Credits and Payments"],
    "schedule_d": ["SCHEDULE D", "Capital Gains and Losses", "capital loss carryover"],
    "it201_p1": ["New York additions", "New York subtractions", "New York adjusted gross income"],
    "it201_p2": ["NYS tax on line 38", "NYS household credit", "Resident credit"],
    "it201_p3": ["Total New York State taxes", "Yonkers resident income tax surcharge"],
    "it201_p4": ["Total New York State tax withheld", "Total New York City tax withheld"],
}

# Pages containing these strings are NY state forms — keep them out of federal sections
_NY_MARKERS = ["IT-201", "IT-196", "IT-255", "IT-201-ATT", "Department of Taxation and Finance"]

_SYSTEM_PROMPT = """\
You are a tax data extraction specialist. You will be given raw text extracted
from a filed US federal and/or NY state income tax return (likely generated by
TurboTax). Extract the requested line items as JSON.

Rules:
- All amounts must be positive integers or decimals (no dollar signs, no commas).
- If a line is blank, missing, or zero, use 0.
- Do not guess or infer amounts you cannot see in the text.
- Include any unusual items, credits, or taxes you notice in the "notes" array.
- For NY IT-201 fields, "itemized" is true when the deduction came from Form IT-196.
"""


def _page_matches(text: str, keywords: list[str]) -> bool:
    t = text.lower()
    return any(kw.lower() in t for kw in keywords)


def _is_ny_page(text: str) -> bool:
    t = text.lower()
    return any(m.lower() in t for m in _NY_MARKERS)


def _collect_pages(pdf_path: Path) -> dict[str, str]:
    """Extract text from relevant pages, keyed by section name."""
    sections: dict[str, list[str]] = {k: [] for k in _WANT_KEYWORDS}

    with fitz.open(str(pdf_path)) as doc:
        for page in doc:
            text = page.get_text("text") or ""
            is_ny = _is_ny_page(text)
            for section, keywords in _WANT_KEYWORDS.items():
                # Prevent NY pages bleeding into federal sections and vice-versa
                if section.startswith("it201") and not is_ny:
                    continue
                if not section.startswith("it201") and is_ny:
                    continue
                if _page_matches(text, keywords):
                    sections[section].append(text)

    return {k: "\n\n---\n\n".join(v) for k, v in sections.items() if v}


def _extract_1040_regex(sections: dict[str, str]) -> dict:
    """
    Deterministically extract 1040 line items using regex.

    TurboTax renders 1040 lines as:  "16 95,533."  or  "1a 408,673."
    We match each known line label followed by its dollar amount.
    """
    text = "\n".join(sections.get(k, "") for k in ("form_1040_p1", "form_1040_p2"))

    def get(patterns: list[str]) -> Decimal:
        for pat in patterns:
            m = re.search(pat, text)
            if m:
                raw = m.group(1).replace(",", "").rstrip(".")
                try:
                    return Decimal(raw)
                except Exception:
                    pass
        return Decimal(0)

    # Schedule 1, 2, 3 detail
    sched_text = "\n".join(
        sections.get(k, "") for k in ("schedule_1", "schedule_2", "schedule_3")
    )

    def get_s(patterns: list[str]) -> Decimal:
        for pat in patterns:
            m = re.search(pat, sched_text)
            if m:
                raw = m.group(1).replace(",", "").rstrip(".")
                try:
                    return Decimal(raw)
                except Exception:
                    pass
        return Decimal(0)

    return {
        "line1a_wages":            get([r"1a\s+([\d,]+\.?\d*)"]),
        "line2b_taxable_interest": get([r"2b\s+Taxable interest[.\s]+([\d,]+\.?\d*)", r"\b2b\s+([\d,]+\.?\d*)"]),
        # 3a/3b: on TurboTax the format is "3a <blank> b Ordinary dividends 3b <amount>"
        # qualified divs are blank if zero; match the amount only if digits follow 3a directly
        "line3a_qualified_dividends": get([r"(?m)^\s*3a\s+([\d,]+\.?\d*)\s*$"]),
        "line3b_ordinary_dividends":  get([r"(?m)^\s*3b\s+([\d,]+\.?\d*)\s*$", r"\b3b\s+([\d,]+\.?\d*)"]),
        "line4b_ira_distributions":   get([r"4b\s+Taxable amount[.\s]+([\d,]+\.?\d*)", r"\b4b\s+([\d,]+\.?\d*)"]),
        "line5b_pensions_annuities":  get([r"5b\s+Taxable amount[.\s]+([\d,]+\.?\d*)", r"\b5b\s+([\d,]+\.?\d*)"]),
        "line6b_taxable_ss":          get([r"6b\s+Taxable amount[.\s]+([\d,]+\.?\d*)", r"\b6b\s+([\d,]+\.?\d*)"]),
        "line7_capital_gain_loss":    get([r"\b7\s+Capital gain[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)7\s+([\d,]+\.?\d*)\s*\n"]),
        "line8_other_income":         get([r"\b8\s+Additional income[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)8\s+([\d,]+\.?\d*)\s*\n"]),
        "line9_total_income":         get([r"\b9\s+Add lines[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)9\s+([\d,]+\.?\d*)\s*\n"]),
        "line10_adjustments":         get([r"\b10\s+Adjustments[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)10\s+([\d,]+\.?\d*)"]),
        "line11_agi":                 get([r"\b11\s+Subtract[^.]+income[.\s]+([\d,]+\.?\d*)", r"(?<!\d)11\s+([\d,]+\.?\d*)"]),
        "line12_deduction":           get([r"\b12\s+Standard[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)12\s+([\d,]+\.?\d*)"]),
        "line13_qbi_deduction":       get([r"\b13\s+Qualified business[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)13\s+([\d,]+\.?\d*)"]),
        "line15_taxable_income":      get([r"\b15\s+Subtract line[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)15\s+([\d,]+\.?\d*)"]),
        # Line 16: TurboTax format is "Tax and 16 Tax (see instructions)... . . 16 95,533."
        # The amount follows the SECOND occurrence of "16" on the same line
        "line16_tax":                 get([r"\. \. 16\s+([\d,]+\.?\d*)", r"(?:Form\(s\): \d \d+.+)\. \. 16\s+([\d,]+\.?\d*)"]),
        "line17_additional_tax":      get([r"\b17\s+Amount from Schedule 2[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)17\s+([\d,]+\.?\d*)"]),
        "line19_ctc":                 get([r"\b19\s+Child tax[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)19\s+([\d,]+\.?\d*)"]),
        "line20_other_credits":       get([r"\b20\s+Amount from Schedule 3[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)20\s+([\d,]+\.?\d*)"]),
        "line23_other_taxes":         get([r"\b23\s+Other taxes[^.]+\.\s+([\d,]+\.?\d*)", r"(?<!\d)23\s+([\d,]+\.?\d*)"]),
        "line24_total_tax":           get([r"\b24\s+Add lines[^.]+total tax[.\s]+([\d,]+\.?\d*)", r"(?<!\d)24\s+([\d,]+\.?\d*)"]),
        "line25a_w2_withheld":        get([r"25\s*a\s*Form\(s\) W.2\s*\.+\s*([\d,]+\.?\d*)", r"25a\s+([\d,]+\.?\d*)"]),
        "line25b_1099_withheld":      get([r"25\s*b\s*Form\(s\) 1099\s*\.+\s*([\d,]+\.?\d*)", r"25b\s+([\d,]+\.?\d*)"]),
        "line25c_other_withheld":     get([r"25\s*c\s*Other forms\s*[.\s]+([\d,]+\.?\d*)", r"25c\s+([\d,]+\.?\d*)"]),
        "line26_estimated_payments":  get([r"(?<!\d)26\s+([\d,]+\.?\d*)\s*\n"]),
        "line33_total_payments":      get([r"\b33\s+Add lines[^.]+payments[.\s]+([\d,]+\.?\d*)", r"(?<!\d)33\s+([\d,]+\.?\d*)"]),
        "line37_balance_due":         get([r"\b37\s+Subtract[^.]+owe[.\s]+([\d,]+\.?\d*)", r"(?<!\d)37\s+([\d,]+\.?\d*)"]),
        "line35a_refund":             get([r"35\s*a\s*Amount[^.]+refunded[.\s]+([\d,]+\.?\d*)", r"35a\s+([\d,]+\.?\d*)"]),
        # Schedule 2 detail
        "additional_medicare_tax":    get_s([r"\b11\s+Additional Medicare[^.]+\.\s+([\d,]+\.?\d*)", r"Additional Medicare Tax[.\s]+([\d,]+\.?\d*)"]),
        "niit":                       get_s([r"\b12\s+Net investment income[^.]+\.\s+([\d,]+\.?\d*)"]),
        "se_tax":                     get_s([r"\b4\s+Self.employment tax[^.]+\.\s+([\d,]+\.?\d*)"]),
        "ev_credit_repayment":        get_s([r"1b\s+([\d,]+\.?\d*)", r"clean vehicle credit[^.]+\.\s+([\d,]+\.?\d*)"]),
        # Schedule 3 detail
        "dependent_care_credit":      get_s([r"\b2\s+Credit for child[^.]+\.\s+([\d,]+\.?\d*)"]),
        "residential_energy_credit":  get_s([r"5a\s+Residential[^.]+\.\s+([\d,]+\.?\d*)"]),
        "clean_vehicle_credit":       get_s([r"6f\s+Clean vehicle[^.]+\.\s+([\d,]+\.?\d*)"]),
    }


def _number_block(text: str) -> list[Decimal]:
    """
    Extract the pure-number block TurboTax prints at the bottom of each IT-201 page.

    Each page ends with a sequence of number-only lines (plus SSN and a form code).
    We discard:
      - 9-digit SSNs (e.g. 171701869)
      - 12-digit form codes (e.g. 201002244555)
    and return the remaining numbers in order.
    """
    nums: list[Decimal] = []
    for line in text.split("\n"):
        s = line.strip()
        if re.match(r"^\d+$", s):
            if len(s) == 9 or len(s) == 12:  # SSN or form-code
                continue
            try:
                nums.append(Decimal(s))
            except Exception:
                pass
    return nums


def _extract_it201_regex(sections: dict[str, str]) -> dict | None:
    """
    Deterministically extract IT-201 line items from the positional value blocks
    that TurboTax prints at the bottom of each IT-201 page.

    Page structure (TurboTax IT-201 layout, positions 0-indexed):

    it201_p1 (lines 1-37 of form):
      [0] line 17 (total federal income)
      [1] line 18 (federal adjustments)
      [2] line 24 - line 19 (net NY additions, usually 0)
      [3] line 33 (NY AGI)
      [4] line 34 (NY deduction)
      [5] line 35 (NY income after deduction)
      [6] line 36 (dependent count)
      [7] line 37 (NY taxable income)

    it201_p2 (lines 38-61):
      [0] line 38 (NY taxable, = line 37)
      [1] line 39 (NY state tax)
      [2] credits subtotal
      [3] line 43 (total credits)
      [4] line 44 (NY tax after credits)
      [5] line 46 (total NY state tax)
      [6] NYC tax (0 if not NYC resident)
      [7] line 61 (total NY + city tax)

    it201_p4 (payments/refund):
      [0] line 62 (carry from line 61)
      [1] line 63 (Empire State child credit, or first refundable credit)
      [2] line 72 (NY withheld)
      [3] line 76 (total payments)
      [4] line 77 (overpaid)
      [5] line 78 (refund amount)
      [6] line 78b (net refund after 529)
    """
    p1 = _number_block(sections.get("it201_p1", ""))
    p2 = _number_block(sections.get("it201_p2", ""))
    p4 = _number_block(sections.get("it201_p4", ""))

    if not p1 and not p2:
        return None

    def _at(block: list[Decimal], idx: int) -> Decimal:
        return block[idx] if idx < len(block) else Decimal(0)

    federal_agi = _at(p1, 3) or _at(p1, 0)
    ny_deduction = _at(p1, 4)
    ny_taxable = _at(p1, 7)
    dep_count = _at(p1, 6)
    ny_dep_exemptions = dep_count * Decimal(1000) if dep_count < 10 else dep_count

    ny_state_tax = _at(p2, 1)
    ny_credits = _at(p2, 3)
    ny_tax_after_credits = _at(p2, 4)
    total_state_tax = _at(p2, 5)
    nyc_tax = _at(p2, 6)
    total_ny_tax = _at(p2, 7) or total_state_tax + nyc_tax

    empire_state_ctc = _at(p4, 1)   # IT-201 line 63 — Empire State child credit (refundable)
    ny_withheld = _at(p4, 2)
    ny_total_payments = _at(p4, 3)
    ny_overpaid = _at(p4, 4)
    ny_refund = _at(p4, 5) or ny_overpaid
    ny_balance = max(Decimal(0), total_ny_tax - ny_total_payments)

    # Detect itemized: deduction differs from ALL common NY standard deductions.
    # We don't know the filing status here, so compare against all status amounts.
    # If the extracted deduction matches none within a $500 tolerance, assume itemized.
    ny_std_amounts = {Decimal("8000"), Decimal("11200"), Decimal("16050")}  # single, HOH, MFJ
    itemized = bool(
        ny_deduction
        and all(abs(ny_deduction - std) > Decimal("500") for std in ny_std_amounts)
    )

    return {
        "federal_agi": federal_agi,
        "ny_additions": Decimal(0),
        "ny_subtractions": Decimal(0),
        "ny_agi": federal_agi,
        "ny_deduction": ny_deduction,
        "ny_dependent_exemptions": ny_dep_exemptions,
        "ny_taxable_income": ny_taxable,
        "ny_state_tax": ny_state_tax,
        "ny_credits": ny_credits,
        "ny_tax_after_credits": ny_tax_after_credits,
        "nyc_tax": nyc_tax,
        "yonkers_surcharge": Decimal(0),
        "total_ny_tax": total_ny_tax,
        "empire_state_ctc": empire_state_ctc,
        "ny_withheld": ny_withheld,
        "nyc_withheld": Decimal(0),
        "ny_balance_due": ny_balance,
        "ny_refund": ny_refund,
        "itemized": itemized,
    }


def _llm_extract(sections: dict[str, str], tax_year: int) -> dict:
    """Send the collected text to GPT-4o for structured extraction."""
    client = get_client()

    # LLM only handles IT-201 (complex layout) and carry-forward items.
    # Form 1040 fields are extracted deterministically by regex (see _extract_1040_regex).
    schema = {
        "it201": None,
        "capital_loss_carryover": 0,
        "estimated_tax_applied": 0,
        "schedule_d_carryover": 0,
        "notes": [],
    }

    it201_schema = {
        "federal_agi": 0,
        "ny_additions": 0,
        "ny_subtractions": 0,
        "ny_agi": 0,
        "ny_deduction": 0,
        "ny_dependent_exemptions": 0,
        "ny_taxable_income": 0,
        "ny_state_tax": 0,
        "ny_credits": 0,
        "ny_tax_after_credits": 0,
        "nyc_tax": 0,
        "yonkers_surcharge": 0,
        "total_ny_tax": 0,
        "empire_state_ctc": 0,
        "ny_withheld": 0,
        "nyc_withheld": 0,
        "ny_balance_due": 0,
        "ny_refund": 0,
        "itemized": False,
    }

    # Prioritise the most critical sections: 1040 p2 (tax/payments), IT-201, then the rest
    priority_order = [
        "form_1040_p2", "form_1040_p1",
        "it201_p4", "it201_p3", "it201_p2", "it201_p1",
        "schedule_2", "schedule_3", "schedule_1", "schedule_d",
    ]
    ordered = []
    for key in priority_order:
        if key in sections:
            ordered.append(f"[SECTION: {key}]\n{sections[key]}")
    for key, text in sections.items():
        if key not in priority_order:
            ordered.append(f"[SECTION: {key}]\n{text}")
    combined_ordered = redact_pii("\n\n========\n\n".join(ordered))

    prompt = f"""\
Tax year: {tax_year}

The following text was extracted from a New York State IT-201 income tax return.
Extract only the NY-specific values into the JSON schema below.

IT-201 field guide (from the return page text or numbers at the bottom of each page):
- federal_agi: NY IT-201 line 19 (Federal adjusted gross income)
- ny_additions: NY additions total (line 24 minus line 19)
- ny_subtractions: NY subtractions total (line 32)
- ny_agi: NY line 33 (NY adjusted gross income)
- ny_deduction: NY line 34 (standard or itemized NY deduction)
- ny_dependent_exemptions: dollar value on NY line 36 (number of dependents × $1,000)
- ny_taxable_income: NY line 37
- ny_state_tax: NY line 39
- ny_credits: total of NY lines 40–43 (household credit + resident credit + other credits)
- ny_tax_after_credits: NY line 44
- nyc_tax: NYC tax (line 49 or 52 or 54)
- yonkers_surcharge: Yonkers line 55
- total_ny_tax: NY line 61
- empire_state_ctc: NY line 63 (Empire State child credit - refundable, may be 0)
- ny_withheld: line 72 (Total New York State tax withheld)
- nyc_withheld: line 73
- ny_balance_due: line 80
- ny_refund: line 78 (amount overpaid / refund)
- itemized: true if they used IT-196 (itemized NY deductions), false for standard

Also extract:
- capital_loss_carryover: net capital loss to carry forward (from Schedule D, negative if loss)
- estimated_tax_applied: amount of prior year refund applied to next year's estimated tax
- notes: list any unusual items, credits, or taxes you notice

Target schema:
{json.dumps({**schema, "it201": it201_schema}, indent=2)}

Return ONLY valid JSON matching the schema above.

--- NY RETURN TEXT ---
{combined_ordered[:20000]}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    return json.loads(response.choices[0].message.content)


def _to_decimal(val) -> Decimal:
    if val is None:
        return Decimal(0)
    s = str(val).replace(",", "").replace("$", "").strip()
    if not s or s in ("null", "None"):
        return Decimal(0)
    try:
        return Decimal(s)
    except Exception:
        return Decimal(0)


def _build_return(raw_llm: dict, raw_regex: dict, tax_year: int, source_file: str) -> PriorYearReturn:
    # Merge: regex provides 1040 fields, LLM provides IT-201 and carry-forwards
    f = raw_regex

    form_1040 = PriorYearForm1040(
        line1a_wages=_to_decimal(f.get("line1a_wages")),
        line2b_taxable_interest=_to_decimal(f.get("line2b_taxable_interest")),
        line3a_qualified_dividends=_to_decimal(f.get("line3a_qualified_dividends")),
        line3b_ordinary_dividends=_to_decimal(f.get("line3b_ordinary_dividends")),
        line4b_ira_distributions=_to_decimal(f.get("line4b_ira_distributions")),
        line5b_pensions_annuities=_to_decimal(f.get("line5b_pensions_annuities")),
        line6b_taxable_ss=_to_decimal(f.get("line6b_taxable_ss")),
        line7_capital_gain_loss=_to_decimal(f.get("line7_capital_gain_loss")),
        line8_other_income=_to_decimal(f.get("line8_other_income")),
        line9_total_income=_to_decimal(f.get("line9_total_income")),
        line10_adjustments=_to_decimal(f.get("line10_adjustments")),
        line11_agi=_to_decimal(f.get("line11_agi")),
        line12_deduction=_to_decimal(f.get("line12_deduction")),
        line13_qbi_deduction=_to_decimal(f.get("line13_qbi_deduction")),
        line15_taxable_income=_to_decimal(f.get("line15_taxable_income")),
        line16_tax=_to_decimal(f.get("line16_tax")),
        line17_additional_tax=_to_decimal(f.get("line17_additional_tax")),
        line19_ctc=_to_decimal(f.get("line19_ctc")),
        line20_other_credits=_to_decimal(f.get("line20_other_credits")),
        line23_other_taxes=_to_decimal(f.get("line23_other_taxes")),
        line24_total_tax=_to_decimal(f.get("line24_total_tax")),
        line25a_w2_withheld=_to_decimal(f.get("line25a_w2_withheld")),
        line25b_1099_withheld=_to_decimal(f.get("line25b_1099_withheld")),
        line25c_other_withheld=_to_decimal(f.get("line25c_other_withheld")),
        line26_estimated_payments=_to_decimal(f.get("line26_estimated_payments")),
        line33_total_payments=_to_decimal(f.get("line33_total_payments")),
        line37_balance_due=_to_decimal(f.get("line37_balance_due")),
        line35a_refund=_to_decimal(f.get("line35a_refund")),
        additional_medicare_tax=_to_decimal(f.get("additional_medicare_tax")),
        niit=_to_decimal(f.get("niit")),
        se_tax=_to_decimal(f.get("se_tax")),
        ev_credit_repayment=_to_decimal(f.get("ev_credit_repayment")),
        dependent_care_credit=_to_decimal(f.get("dependent_care_credit")),
        residential_energy_credit=_to_decimal(f.get("residential_energy_credit")),
        clean_vehicle_credit=_to_decimal(f.get("clean_vehicle_credit")),
    )

    schedule_d = PriorYearScheduleD(
        carryover_to_next_year=_to_decimal(raw_llm.get("schedule_d_carryover")),
    )

    it201 = None
    ny_raw = raw_llm.get("it201")
    if ny_raw and isinstance(ny_raw, dict):
        it201 = PriorYearIT201(
            federal_agi=_to_decimal(ny_raw.get("federal_agi")),
            ny_additions=_to_decimal(ny_raw.get("ny_additions")),
            ny_subtractions=_to_decimal(ny_raw.get("ny_subtractions")),
            ny_agi=_to_decimal(ny_raw.get("ny_agi")),
            ny_deduction=_to_decimal(ny_raw.get("ny_deduction")),
            ny_dependent_exemptions=_to_decimal(ny_raw.get("ny_dependent_exemptions")),
            ny_taxable_income=_to_decimal(ny_raw.get("ny_taxable_income")),
            ny_state_tax=_to_decimal(ny_raw.get("ny_state_tax")),
            ny_credits=_to_decimal(ny_raw.get("ny_credits")),
            ny_tax_after_credits=_to_decimal(ny_raw.get("ny_tax_after_credits")),
            nyc_tax=_to_decimal(ny_raw.get("nyc_tax")),
            yonkers_surcharge=_to_decimal(ny_raw.get("yonkers_surcharge")),
            total_ny_tax=_to_decimal(ny_raw.get("total_ny_tax")),
            empire_state_ctc=_to_decimal(ny_raw.get("empire_state_ctc")),
            ny_withheld=_to_decimal(ny_raw.get("ny_withheld")),
            nyc_withheld=_to_decimal(ny_raw.get("nyc_withheld")),
            ny_balance_due=_to_decimal(ny_raw.get("ny_balance_due")),
            ny_refund=_to_decimal(ny_raw.get("ny_refund")),
            itemized=bool(ny_raw.get("itemized", False)),
        )

    return PriorYearReturn(
        tax_year=tax_year,
        source_file=source_file,
        form_1040=form_1040,
        schedule_d=schedule_d,
        it201=it201,
        capital_loss_carryover=_to_decimal(raw_llm.get("capital_loss_carryover")),
        estimated_tax_applied=_to_decimal(raw_llm.get("estimated_tax_applied")),
        notes=raw_llm.get("notes", []),
    )


def ingest_prior_year_return(pdf_path: Path, tax_year: int | None = None) -> PriorYearReturn:
    """
    Parse a prior-year PDF return and return a structured PriorYearReturn.

    The tax year is inferred from the filename (e.g. '2024_TaxReturn.pdf' → 2024)
    if not provided explicitly.

    Args:
        pdf_path: Path to the prior-year PDF.
        tax_year: Override for the tax year (e.g. 2024).

    Returns:
        PriorYearReturn with extracted line items.
    """
    pdf_path = Path(pdf_path)

    if tax_year is None:
        m = re.search(r"20\d\d", pdf_path.stem)
        tax_year = int(m.group()) if m else 2024

    sections = _collect_pages(pdf_path)
    if not sections:
        raise ValueError(f"No recognisable tax return pages found in {pdf_path}")

    # Pass 1: deterministic regex for Form 1040 fields
    raw_regex = _extract_1040_regex(sections)

    # Pass 2: deterministic regex for IT-201 (if present)
    it201_regex = _extract_it201_regex(sections)

    # Pass 3: LLM for carry-forward items and any items regex can't catch
    raw_llm = _llm_extract(sections, tax_year)

    # Prefer regex IT-201 over LLM IT-201 (more reliable)
    if it201_regex:
        raw_llm["it201"] = it201_regex

    return _build_return(raw_llm, raw_regex, tax_year, str(pdf_path))
